apiVersion: v1
kind: Pod
metadata:
  name: order-processing
  labels:
    app: order-processing
spec:
  containers:
    - name: order-processing
      image: amaurii/order-processing:latest
      ports:
        - containerPort: 8080
      env:
        - name: MONGO_URI
          value: "mongodb://mongodb:27017"
        - name: RABBITMQ_URL
          value: "amqp://guest:guest@rabbitmq:5672"
        - name: REDIS_HOST
          value: "redis"
        - name: REDIS_PORT
          value: "6379"
