server:
  port: 8080

spring:
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest
    listener:
      simple:
        acknowledge-mode: manual
  data:
    mongodb:
      host: mongodb
      port: 27017
      database: orders_db
      username: admin
      password: guest
      authentication-database: admin
    redis:
      host: redis
      port: 6379

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    prometheus:
      enabled: true
  prometheus:
    metrics:
      export:
        enabled: true


logging:
  level:
    root: INFO
    com.example.payment: DEBUG
    org.springframework.cloud.aws.messaging.listener: DEBUG
