apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
        - name: rabbitmq
          image: rabbitmq:3-management
          ports:
            - containerPort: 5672  # Porta para mensagens
            - containerPort: 15672 # Porta para interface web
          env:
            - name: RABBITMQ_DEFAULT_USER
              value: "guest"
            - name: RABBITMQ_DEFAULT_PASS
              value: "guest"

---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
spec:
  selector:
    app: rabbitmq
  ports:
    - name: "amqp"   # Nome único para a porta AMQP
      protocol: TCP
      port: 5672
      targetPort: 5672
    - name: "management" # Nome único para a interface de gerenciamento
      protocol: TCP
      port: 15672
      targetPort: 15672
  type: ClusterIP
