apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
spec:
  selector:
    app: rabbitmq
  ports:
    - name: amqp
      protocol: TCP
      port: 5672
      targetPort: 5672
      nodePort: 32072
    - name: management
      protocol: TCP
      port: 15672
      targetPort: 15672
      nodePort: 32073
  type: NodePort
